### ISSUE TITLE
[Bug] unable to run UpdateRemotePlugins

### ISSUE THREAD

**Issue by SamDc73** [dccsillag/magma-nvim#45]
**Describe the bug**
whenever i run :UpdateRemotePlugins` i got this error 
```
Encountered ImportError loading plugin at /home/user/.local/share/nvim/site/pack/packer/start/magma-nvim/rplugin
/python3/magma: libffi.so.6: cannot open shared object file: No such file or directory                             
Traceback (most recent call last):                                                                                 
  File "/home/user/.local/lib/python3.9/site-packages/pynvim/plugin/host.py", line 165, in _load                
    module = imp.load_module(name, file, pathname, descr)                                                          
  File "/home/user/.config/pyenv/versions/3.9.12/lib/python3.9/imp.py", line 244, in load_module                
    return load_package(name, filename)                                                                            
  File "/home/user/.config/pyenv/versions/3.9.12/lib/python3.9/imp.py", line 216, in load_package               
    return _load(spec)                                                                                             
  File "<frozen importlib._bootstrap>", line 711, in _load                                                         
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked                                                
ImportError: libffi.so.6: cannot open shared object file: No such file or directory                                
remote/host: python3 host registered plugins []                                                                    
remote/host: generated rplugin manifest: /home/user/.local/share/nvim/rplugin.vim  
```

**Desktop (please complete the following information):**
 - OS: Linux Fedora 36 
 - Browser Firefox, ungoogled chromium
 - Python Version 3.9.12 
 - neovim version 0.7.0

**Additional context**
 I'm using pyenv and i have `vim.g['python3_host_prog'] = '~/.config/pyenv/shims/python3'` set in my config file . Note that i have all the dependencies up and running well with no problems
If i use my system's python then i will have another problem with ueberzug since it dosen't seem to work under python 3.10

**Comment by airpods69** [comment]
what is the output ```:checkhealth```? you might find the error in that

**Comment by dccsillag** [comment]
The problem seems to happen because libffi 'version 6' is not installed. Can you look for `libffi.so.*` in your machine (e.g. via `find / -name 'libffi.so.*'`)?
