### ISSUE TITLE
Error while using visual evaluate

### ISSUE THREAD

**Issue by Paracelsus-Rose** [dccsillag/magma-nvim#66]
Not sure If I am misusing visual evaluate mode, but the best way to describe how I am getting this error message is as follows.

1. Open new test.py file
2. :MagmaInit select python3
3. Write code block
```python
a = 1
b = 2
print(a+b)
```
4. Select Code block with visual select, run :MagmaEvaluateVisual
This works as expected
5. Enter two blank lines and write this code block
```python
c = 3
print(c)
```
6. Once again evaluate visual, this works.
7.  Insert this code block 2 lines lower
```python
d = a + b + c
print(d)
```
8. From here, when I select the code block, evaluate visual, and try and move up in the buffer, I get this error
```
Error detected while processing CursorMoved Autocommands for "*"..function MagmaUpdateInterface[1]..remote#define#request:                                                                
line    2:                                                                                                                                                                                
Error invoking '/home/chris/.local/share/nvim/site/pack/packer/start/magma-nvim/rplugin/python3/magma:function:MagmaUpdateInterface' on channel 5 (python3-rplugin-host):                  
error caught in request handler '/home/chris/.local/share/nvim/site/pack/packer/start/magma-nvim/rplugin/python3/magma:function:MagmaUpdateInterface [[]]':                                
Traceback (most recent call last):                                                                                                                                                        
  File "/home/chris/.local/share/nvim/site/pack/packer/start/magma-nvim/rplugin/python3/magma/utils.py", line 13, in inner                                                                 
    func(self, *args, **kwargs)                                                                                                                                                           
  File "/home/chris/.local/share/nvim/site/pack/packer/start/magma-nvim/rplugin/python3/magma/__init__.py", line 419, in function_update_interface                                         
    self._update_interface()                                                                                                                                                              
  File "/home/chris/.local/share/nvim/site/pack/packer/start/magma-nvim/rplugin/python3/magma/__init__.py", line 125, in _update_interface                                                 
    magma.update_interface()                                                                                                                                                              
  File "/home/chris/.local/share/nvim/site/pack/packer/start/magma-nvim/rplugin/python3/magma/magmabuffer.py", line 203, in update_interface                                               
    self._show_selected(self.selected_cell)                                                                                                                                               
  File "/home/chris/.local/share/nvim/site/pack/packer/start/magma-nvim/rplugin/python3/magma/magmabuffer.py", line 246, in _show_selected                                                 
    self.outputs[span].show(span.end)                                                                                                                                                     
  File "/home/chris/.local/share/nvim/site/pack/packer/start/magma-nvim/rplugin/python3/magma/outputbuffer.py", line 106, in show                                                          
    assert self.display_window is None                                                                                                                                                    
AssertionError    
```

From here I am not sure what to do, how to check into things, or offer any insight.  
:checkhealth is good

Neovim 0.9
Ubunutu 22.04
Python 3.10.7

Love the plugin so far, appreciate the hard work on it :-)

**Comment by WhiteBlackGoose** [comment]
Feel free to reopen, but it doesn't seem to have problems by now

![re-mag](https://github.com/dccsillag/magma-nvim/assets/31178401/79647af6-14b7-4f02-93cd-faecb0248c35)
