### ISSUE TITLE
[Bug] error when mannually  try :UpdateRemotePlugins(all dependencies installed)

### ISSUE THREAD

**Issue by puppyapple** [dccsillag/magma-nvim#67]
Encountered TypeError loading plugin at /home/puppyapple/.local/share/lunarvim/site/pack/packer/start/magma-nvim/rplugin/python3/magma: 'ABCMeta' object is not subscriptable
Traceback (most recent call last):
  File "/home/puppyapple/anaconda3/envs/py38/lib/python3.8/site-packages/pynvim/plugin/host.py", line 165, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/home/puppyapple/anaconda3/envs/py38/lib/python3.8/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/home/puppyapple/anaconda3/envs/py38/lib/python3.8/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
TypeError: 'ABCMeta' object is not subscriptable
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /home/puppyapple/.local/share/nvim/rplugin.vim

**Comment by vanducng** [comment]
Got same issue, I think it resulted due to [this commit](https://github.com/dccsillag/magma-nvim/commit/ce56a23419413bbc5916eabb57b77991cffca273#diff-bf0edb5681796412ce9623ec07cff4560a685dc988566cfd1a93585ce429d489).

I temporary install from a commit previously.
```
use { "lukas-reineke/virt-column.nvim", commit = "36fa3be9cba9195081e934b4f9729021726c5889" }
```

**Comment by Slownite** [comment]
Are they any permanent solutions?

**Comment by gallavee** [comment]
using python 3.9 fixed this for me

**Comment by WhiteBlackGoose** [comment]
[eca28c6](https://github.com/dccsillag/magma-nvim/commit/eca28c66c38e203316a7eab03340e1618d12fa59) should fix it
